# Generated by Django 2.2 on 2019-08-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilefeedItem',
        ),
    ]
